project:
  type: website

website:
  title: "Zhuowei Deng"
  navbar:
    right:
      - href: index.qmd
        text: Landing
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto